### ISSUE TITLE
Test closed loop system

### ISSUE THREAD

**Issue by dragly** [CINPLA/open-ephys-plugin-GUI#20]
Make sure we can send a random tracking path to the Open Ephys plugins and be able to record the right stimulation distribution back in the Open Ephys after stimulating through the Pulse Pal.

Data goes in the pipeline as follows:

- Random data from Python script
- OSC
- Tracking port plugin
- Tracking stim plugin
- Pulse pal plugin to TTL
- Connections?
- Open Ephys recording of TTL
- Storage?

I need information about the following:

1. How to generate the random data? Do we have a script? If so, where? If not, what should the data look like? What makes it realistic?
2. How do we plug the pulse pal to the Open Ephys for TTL recording? Links?
3. How do we set up the Open Ephys hardware? Links?
4. How do we store the recorded data?

**Comment by alejoe91** [comment]
1. I just pushed a random_path code that creates 10 sources and sends them on 10 different OSC ports and addresses.
2. To plug in the pulse pal to the open ephys you need the I/O board. we have plenty. I will ask Malin to get one for you.
3. to install the hardware see: [https://open-ephys.atlassian.net/wiki/spaces/OEW/pages/491546/Linux](url). The Rhythm FPGA is the plugin to record data. When you add it to the signal chain it's going to ask you to locate the bit stream file to program the FPGA, located in Resources/Bitfiles/rhd_2000.bit
4. save the data as binary. We have used it before and we will provide python code to parse it in that format. All events are saved in npy array. Working on the parser.

@dragly: everything clear? :)
